language: julia
os:
  - linux
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
codecov: true
coveralls: true

## uncomment the following lines to override the default test script
# script:
#   - julia -e 'import Pkg; Pkg.clone("https://github.com/konkam/FeynmanKacParticleFilters.jl.git"); Pkg.test("FeynmanKacParticleFilters"; coverage=true);'
# after_success:
#   # push coverage results to Coveralls
#   - julia --inline=no --project --code-coverage=user -e 'import Pkg; cd(Pkg.dir("FeynmanKacParticleFilters")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#   # push coverage results to Codecov
#   - julia --inline=no --project --code-coverage=user -e 'import Pkg; cd(Pkg.dir("FeynmanKacParticleFilters")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
